### ISSUE TITLE
LED's On Off

### ISSUE THREAD

**Issue by deckchairhq** [pimoroni/pxt-envirobit#1]
Hi, I think we need a new release on this...

I also recommend moving development to a "develop" branch, as otherwise users will Google and find these instructions, but the README on Master is of course for the latest "in-dev" version not the released version.

The onClap event that I *think* you've added in recent commits looks much easier than listening for 2500ms in an if statement, within the forever loop... We wanted to use the forever loop for other things...

Also, i've noticed that the LED's don't work - is this a malfunction with my hardware or something that will be fixed in next release?

Here is the script (generated by blocks) that doesn't work for us:

envirobit.setLEDs(envirobit.OnOff.On)
basic.pause(1000)

Best,

Gareth

**Comment by deckchairhq** [comment]
I should add that our end goal is to leave it running permenantly listening for claps. 

When it receives a clap it turns on/off connected neopixels

We wanted to attach colour detection to the A or B button - which in turn would set the colour of the neopixels... not quite sure if it will like us using a pin for neopixels dateline whilst envirobit is connected - will find out soon enough :)

**Comment by Gadgetoid** [comment]
Some solid points here- I didn't think of the rift it would leave in documentation.

As far as I know, the LEDs work- they do on my unit in any case. There could be a fault, dry joint, loose connection etc on yours, or potentially some other code that's interfering with the operation of the pin the LEDs use.

I'll tag up a release, since I think the library in its current state is good to go and the onClap is, indeed, much better than waiting for a clap in a loop. Although it's a little finicky since the micro:bit is just interleaving the tasks rather than doing any real multithreading or interrupts on the microphone.
